### ISSUE TITLE
awsome-sentinel-2

### ISSUE THREAD

**Issue by valgur** [Fernerkundung/awesome-sentinel#3]
In case you have not noticed this one yet, a slightly more specific https://github.com/spatialhast/awesome-sentinel-2 list also exists. There's quite a bit of overlap. I guess you might want to copy quite a few things over to this list as well?

**Comment by kr-stn** [comment]
Thanks for the tip, I've already seen that list. I don't want to blindly copy everything - this should be a curated list after all. So I'm trying to check out the tools and see which ones to include here as well.

Anyways - @spatialhast is already adding stuff from the list - see #2.

**Comment by spatialhast** [comment]
I didn't note repository in search and created in my account... Yes, move the necessary links from my repo in awesome-sentinel. I rename my repository in another name.
